version: '3.8'
services:
  assets-manager:
    build: 
      context: ./assets-manager
      dockerfile: Dockerfile
    container_name: assets-manager
    ports:
      - "4200:80"
    restart: unless-stopped
