version: '3.8'
services:
  config-service: 
    image: config-service:0.1
    build:
      context: .
      dockerfile: ./core/config-service/Dockerfile
    ports:
      - "8888:8888"
    environment:
      - GITLAB_USERNAME=bvargasmt1
      - GITLAB_PASSWORD=Onkk941!
    networks:
      - app-network
  registry-service: 
    image: registry-service:0.1
    build:
      context: .
      dockerfile: ./core/registry-service/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - app-network
    depends_on:
      - config-service
  gateway-service:  
    image: gateway-service:0.1
    build:
      context: .
      dockerfile: ./core/gateway-service/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - config-service
      - registry-service
networks:
  app-network:
    driver: bridge