version: '3.8'

services:
  # --- Servicios de Infraestructura ---
  config-service:
    image: config-service:0.1
    build:
      context: ./config-service
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - GITLAB_USERNAME=bvargasmt1
      - GITLAB_PASSWORD=Onkk941!
    networks:
      - app-network

  registry-service:
    image: registry-service:0.1
    build:
      context: ./registry-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - app-network
    depends_on:
      - config-service

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql
      - ./init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql
    networks:
      - app-network

  # --- Gateway y Frontend ---
  gateway-service:
    image: gateway-service:0.1
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - config-service
      - registry-service

  assets-manager:
    build:
      context: ./assets-manager
      dockerfile: Dockerfile
    container_name: assets-manager
    ports:
      - "4200:80"
    restart: unless-stopped
    networks:
      - app-network

  # --- Microservicios ---
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      MYSQL_HOST: mysql-db  # Usar nombre del servicio en red
      MYSQL_PORT: 3306
      MYSQL_DB: auth_service_db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      REGISTER_HOST: registry-service
      REGISTER_PORT: 8761
    ports:
      - "8088:8088"
    depends_on:
      - mysql-db
      - registry-service
    networks:
      - app-network

  asset-service:
    build:
      context: ./asset-service
      dockerfile: Dockerfile
    container_name: asset-service
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_DB: asset_service_db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      REGISTER_HOST: registry-service
      REGISTER_PORT: 8761
    ports:
      - "8089:8089"
    depends_on:
      - mysql-db
      - registry-service
    networks:
      - app-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_DB: notification_service_db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      REGISTER_HOST: registry-service
      REGISTER_PORT: 8761
    ports:
      - "8090:8090"
    depends_on:
      - mysql-db
      - registry-service
    networks:
      - app-network

# --- Configuraciones Globales ---
networks:
  app-network:
    driver: bridge

volumes:
  mysql_db_data:
