server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/api/protected/private/**
          filters:
            - name: AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/api/protected/public/**

        - id: asset-service
          uri: lb://asset-service
          predicates:
            - Path=/asset/**
          filters:
            - name: AuthenticationFilter

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
#          filters:
#            - name: AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  security:
    jwt:
      secret-key: w8rFzL!9Y#ZxPcLm2qT7sGh3NpVdJuKwRbXeSfUgHbJkMnoP
      expiration-time: 900000
      refresh-time: 604800000

allowed.origins:
  http://localhost:4200

#  instance:
#    metadata-map:
#      instanceId: ${spring.application.name}:${spring.application.instance_id}:${random.value}


#management:
#  endpoint:
#    web:
#      exposure:
#        include: *