export enum AssetStatus {
  AVAILABLE = 'AVAILABLE',
  ASIGNED = 'ASIGNED',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
  RETIRED = 'RETIRED',
  OBSOLETE = 'OBSOLETE',
  LOST = 'LOST',
  STOLEN = 'STOLEN',
}
