version: '3.8'
services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql
      - ./init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORRT: 3306
      MYSQL_DB: auth_service_db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      REGISTER_HOST: localhost
      REGISTER_PORT: 8761
    ports:
      - "8088:8088"
    depends_on:
      - mysql-db
  asset-service:
    build:
      context: ./asset-service
      dockerfile: Dockerfile
    container_name: asset-service
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORRT: 3306
      MYSQL_DB: asset_service_db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      REGISTER_HOST: localhost
      REGISTER_PORT: 8761
    ports:
      - "8089:8089"
    depends_on:
      - mysql-db
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORRT: 3306
      MYSQL_DB: notification_service_db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      REGISTER_HOST: localhost
      REGISTER_PORT: 8761
    ports:
      - "8090:8090"
    depends_on:
      - mysql-db    
volumes:
  mysql_db_data: